export { authorizationService } from 'src/services/_authorization.service.js'
export * from 'src/services/_axios'
export { evoService } from 'src/services/_evo.service.js'
export { mailService } from 'src/services/_mail.service.js'
export { minioService } from 'src/services/_minio.service.js'
export * from 'src/services/_prisma.service'
